# -*- coding: utf-8 -*-
"""SPAM E-MAIL .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WUEIcAn5VbpeKfF8fmqDl7zxZmBgawGZ

[link text](https://)SPAM EMAIL DETECTOR NAIVE BAYES ( DATA INFO:::: SPAM = 1 ;HAM =0 )

RELATED PROJECT :: FACEBOOK, YOUTUBE FAKE COMMENT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/emails.csv')
df.head()

df['spam'].value_counts()

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)
#df.dropna(inplace=True)
df

df['spam'].value_counts()

"""TEXT DATA ER JONNO MULTINOMIAL NAIVE BAYES BEST"""

from sklearn.model_selection import train_test_split
#from sklearn.preprocessing import StandardScaler === It is for only numeric data
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

x=df.text.values
y=df.spam.values

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
df

cv=CountVectorizer()
cv.fit(x_train)
x_train_abc=cv.transform(x_train)

x_train_abc.toarray()

model=MultinomialNB()
model.fit(x_train_abc,y_train)

"""TRAIN AND MODEL FITTING FINISH .... NOW ITS THE TIME TO TEST"""

x_test_abc=cv.transform(x_test)

x_test_abc.toarray()

"""MEASURE ACCRUACY"""

model.score(x_test_abc,y_test)

model.score(x_train_abc,y_train)

"""EXAMPLE

"""

mails=[
       'Hey mohan, can we get together to watch footbal game tomorrow?',
       'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

cv_mails=cv.transform(mails)

model.predict(cv_mails)

0= real mail
1= spam